server:
  port: 8081
  context-path: /mydemo
debug: true
spring:
  datasource:
    url: jdbc:p6spy:mysql://localhost:3306/task?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: 123
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
  thymeleaf:
    cache: false
    encoding: UTF-8
    suffix: .html
    mode: LEGACYHTML5 #非严格检查 默认严格检查 #spring.thymeleaf.mode=HTML5

  devtools:
    restart:
    enabled: true  #设置开启热部署
    #设置重启的目录
    additional-paths: resources/**,static/**,templates/**
    freemarker:
      cache: false    #页面不加载缓存，修改即时生效
  mail:
    host: smtp.qq.com
    username: 2469785911@qq.com
    password: fvrpcxjxuvdeecgg
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

mybatis-plus:
  global-config:
    db-config:
      id-type: auto
      field-strategy: not_empty
        #驼峰下划线转换
      column-underline: true
        #逻辑删除配置
      logic-delete-value: 0
      logic-not-delete-value: 1
      db-type: mysql
    refresh: false
  configuration:
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
    cache-enabled: false

mail:
  fromMail:
    addr: 2469785911@qq.com